/**:
    ros__parameters:
        common:
            lidar_topic: "/sensor/lidar_fusion/points"
            imu_topic: "/sensor/vectornav/imu"
            initial_pose_topic: "/sensor/vectornav/position"
            lidar_frame_id: "base_link"
            imu_frame_id: "vectornav_enu"
            # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
            time_offset_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 0 # 0 for undistorted pointclouds
            blind: 4.0

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            cube_side_length: 1000.0
            det_range: 250.0
            max_iteration: 3
            extrinsic_est_en: false # true: enable the online estimation of IMU-LiDAR extrinsic
            filter_size_surf: 0.5
            filter_size_map: 0.5

        publish:
            path_en: true
            scan_publish_en: true # false: close all the point cloud output
            dense_publish_en: true # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true # true: output the point cloud scans in IMU-body-frame
